fixup! (chore): Fixup commit

diff --git a/bin/fixup b/bin/fixup
--- a/bin/fixup
+++ b/bin/fixup
@@ -1,22 +1,23 @@
 #!/usr/bin/env bash
 
-# credit where credit is due...
-title_match="${@:1}"
+function fixup() {
+  title_match="${@:1}"
 
-echo "\nThis operation will rebase:\n"
+  echo "\nThis operation will rebase:\n"
 
-git --no-pager log --oneline "HEAD^{/$title_match}^..HEAD" --reverse
+  git --no-pager log --oneline "HEAD^{/$title_match}^..HEAD" --reverse
 
-if [[ $? -ne 0 ]]; then
-  echo "\nCould not find a commit with title matching: \"$title_match\""
-  return
-fi
+  if [[ $? -ne 0 ]]; then
+    echo "\nCould not find a commit with title matching: \"$title_match\""
+    return
+  fi
 
-echo
-read -q "REPLY?Are you sure? "
-echo
+  echo
+  read -q "REPLY?Are you sure? "
+  echo
 
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
-  git commit --fixup ":/$title_match" && GIT_SEQUENCE_EDITOR=: git rebase --interactive --autostash --autosquash "HEAD^^{/$title_match}^"
-fi
+  if [[ $REPLY =~ ^[Yy]$ ]]
+  then
+    git commit --fixup ":/$title_match" && GIT_SEQUENCE_EDITOR=: git rebase --interactive --autostash --autosquash "HEAD^^{/$title_match}^"
+  fi
+}
